// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARVkNp0S5IAofpfnQcYYjItlhMZUb5bA8',
    appId: '1:228666504651:web:4332e0d8386d830b3fb24e',
    messagingSenderId: '228666504651',
    projectId: 'comic-5ff9a',
    authDomain: 'comic-5ff9a.firebaseapp.com',
    storageBucket: 'comic-5ff9a.appspot.com',
    measurementId: 'G-EH6WY7R0P2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_TjIGrvgZ8wJn0RuDuyHQFvN22r9JxPM',
    appId: '1:228666504651:android:92e5ccd55d95d6af3fb24e',
    messagingSenderId: '228666504651',
    projectId: 'comic-5ff9a',
    storageBucket: 'comic-5ff9a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBolFnIxcm4owzm7GiYykiZmR-lL-_FtnE',
    appId: '1:228666504651:ios:c633469141e45ab63fb24e',
    messagingSenderId: '228666504651',
    projectId: 'comic-5ff9a',
    storageBucket: 'comic-5ff9a.appspot.com',
    iosBundleId: 'com.comic.comic',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBolFnIxcm4owzm7GiYykiZmR-lL-_FtnE',
    appId: '1:228666504651:ios:e9b9ed80c37e328b3fb24e',
    messagingSenderId: '228666504651',
    projectId: 'comic-5ff9a',
    storageBucket: 'comic-5ff9a.appspot.com',
    iosBundleId: 'com.comic.comic.RunnerTests',
  );
}
